# Generated by Django 4.0.3 on 2022-04-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_task', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('task', models.TextField()),
                ('date_ended', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
